/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './pages/__root';
import { Route as LandingImport } from './pages/landing';
import { Route as IndexImport } from './pages/index';
import { Route as EeipReportsIndexImport } from './pages/eeip-reports/index';
import { Route as AdminIndexImport } from './pages/admin/index';
import { Route as CompareDataLayoutImport } from './pages/compare-data/_layout';
import { Route as CompareDataLayoutIndexImport } from './pages/compare-data/_layout/index';
import { Route as CompareDataLayoutNewImport } from './pages/compare-data/_layout/new';
import { Route as CompareDataLayoutCompareImport } from './pages/compare-data/_layout/compare';

// Create Virtual Routes

const CompareDataImport = createFileRoute('/compare-data')();

// Create/Update Routes

const CompareDataRoute = CompareDataImport.update({
  id: '/compare-data',
  path: '/compare-data',
  getParentRoute: () => rootRoute,
} as any);

const LandingRoute = LandingImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const EeipReportsIndexRoute = EeipReportsIndexImport.update({
  id: '/eeip-reports/',
  path: '/eeip-reports/',
  getParentRoute: () => rootRoute,
} as any);

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any);

const CompareDataLayoutRoute = CompareDataLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => CompareDataRoute,
} as any);

const CompareDataLayoutIndexRoute = CompareDataLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareDataLayoutRoute,
} as any);

const CompareDataLayoutNewRoute = CompareDataLayoutNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompareDataLayoutRoute,
} as any);

const CompareDataLayoutCompareRoute = CompareDataLayoutCompareImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => CompareDataLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/landing': {
      id: '/landing';
      path: '/landing';
      fullPath: '/landing';
      preLoaderRoute: typeof LandingImport;
      parentRoute: typeof rootRoute;
    };
    '/compare-data': {
      id: '/compare-data';
      path: '/compare-data';
      fullPath: '/compare-data';
      preLoaderRoute: typeof CompareDataImport;
      parentRoute: typeof rootRoute;
    };
    '/compare-data/_layout': {
      id: '/compare-data/_layout';
      path: '/compare-data';
      fullPath: '/compare-data';
      preLoaderRoute: typeof CompareDataLayoutImport;
      parentRoute: typeof CompareDataRoute;
    };
    '/admin/': {
      id: '/admin/';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/eeip-reports/': {
      id: '/eeip-reports/';
      path: '/eeip-reports';
      fullPath: '/eeip-reports';
      preLoaderRoute: typeof EeipReportsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/compare-data/_layout/compare': {
      id: '/compare-data/_layout/compare';
      path: '/compare';
      fullPath: '/compare-data/compare';
      preLoaderRoute: typeof CompareDataLayoutCompareImport;
      parentRoute: typeof CompareDataLayoutImport;
    };
    '/compare-data/_layout/new': {
      id: '/compare-data/_layout/new';
      path: '/new';
      fullPath: '/compare-data/new';
      preLoaderRoute: typeof CompareDataLayoutNewImport;
      parentRoute: typeof CompareDataLayoutImport;
    };
    '/compare-data/_layout/': {
      id: '/compare-data/_layout/';
      path: '/';
      fullPath: '/compare-data/';
      preLoaderRoute: typeof CompareDataLayoutIndexImport;
      parentRoute: typeof CompareDataLayoutImport;
    };
  }
}

// Create and export the route tree

interface CompareDataLayoutRouteChildren {
  CompareDataLayoutCompareRoute: typeof CompareDataLayoutCompareRoute;
  CompareDataLayoutNewRoute: typeof CompareDataLayoutNewRoute;
  CompareDataLayoutIndexRoute: typeof CompareDataLayoutIndexRoute;
}

const CompareDataLayoutRouteChildren: CompareDataLayoutRouteChildren = {
  CompareDataLayoutCompareRoute: CompareDataLayoutCompareRoute,
  CompareDataLayoutNewRoute: CompareDataLayoutNewRoute,
  CompareDataLayoutIndexRoute: CompareDataLayoutIndexRoute,
};

const CompareDataLayoutRouteWithChildren =
  CompareDataLayoutRoute._addFileChildren(CompareDataLayoutRouteChildren);

interface CompareDataRouteChildren {
  CompareDataLayoutRoute: typeof CompareDataLayoutRouteWithChildren;
}

const CompareDataRouteChildren: CompareDataRouteChildren = {
  CompareDataLayoutRoute: CompareDataLayoutRouteWithChildren,
};

const CompareDataRouteWithChildren = CompareDataRoute._addFileChildren(
  CompareDataRouteChildren
);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/landing': typeof LandingRoute;
  '/compare-data': typeof CompareDataLayoutRouteWithChildren;
  '/admin': typeof AdminIndexRoute;
  '/eeip-reports': typeof EeipReportsIndexRoute;
  '/compare-data/compare': typeof CompareDataLayoutCompareRoute;
  '/compare-data/new': typeof CompareDataLayoutNewRoute;
  '/compare-data/': typeof CompareDataLayoutIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/landing': typeof LandingRoute;
  '/compare-data': typeof CompareDataLayoutIndexRoute;
  '/admin': typeof AdminIndexRoute;
  '/eeip-reports': typeof EeipReportsIndexRoute;
  '/compare-data/compare': typeof CompareDataLayoutCompareRoute;
  '/compare-data/new': typeof CompareDataLayoutNewRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/landing': typeof LandingRoute;
  '/compare-data': typeof CompareDataRouteWithChildren;
  '/compare-data/_layout': typeof CompareDataLayoutRouteWithChildren;
  '/admin/': typeof AdminIndexRoute;
  '/eeip-reports/': typeof EeipReportsIndexRoute;
  '/compare-data/_layout/compare': typeof CompareDataLayoutCompareRoute;
  '/compare-data/_layout/new': typeof CompareDataLayoutNewRoute;
  '/compare-data/_layout/': typeof CompareDataLayoutIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/landing'
    | '/compare-data'
    | '/admin'
    | '/eeip-reports'
    | '/compare-data/compare'
    | '/compare-data/new'
    | '/compare-data/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/landing'
    | '/compare-data'
    | '/admin'
    | '/eeip-reports'
    | '/compare-data/compare'
    | '/compare-data/new';
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/compare-data'
    | '/compare-data/_layout'
    | '/admin/'
    | '/eeip-reports/'
    | '/compare-data/_layout/compare'
    | '/compare-data/_layout/new'
    | '/compare-data/_layout/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LandingRoute: typeof LandingRoute;
  CompareDataRoute: typeof CompareDataRouteWithChildren;
  AdminIndexRoute: typeof AdminIndexRoute;
  EeipReportsIndexRoute: typeof EeipReportsIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  CompareDataRoute: CompareDataRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  EeipReportsIndexRoute: EeipReportsIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/landing",
        "/compare-data",
        "/admin/",
        "/eeip-reports/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/landing": {
      "filePath": "landing.tsx"
    },
    "/compare-data": {
      "filePath": "compare-data",
      "children": [
        "/compare-data/_layout"
      ]
    },
    "/compare-data/_layout": {
      "filePath": "compare-data/_layout.tsx",
      "parent": "/compare-data",
      "children": [
        "/compare-data/_layout/compare",
        "/compare-data/_layout/new",
        "/compare-data/_layout/"
      ]
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/eeip-reports/": {
      "filePath": "eeip-reports/index.tsx"
    },
    "/compare-data/_layout/compare": {
      "filePath": "compare-data/_layout/compare.tsx",
      "parent": "/compare-data/_layout"
    },
    "/compare-data/_layout/new": {
      "filePath": "compare-data/_layout/new.tsx",
      "parent": "/compare-data/_layout"
    },
    "/compare-data/_layout/": {
      "filePath": "compare-data/_layout/index.tsx",
      "parent": "/compare-data/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
